ghdl -a --std=08 --ieee=synopsys "../Final Folder/constDef_pkg.vhd"
ghdl -a --std=08 --ieee=synopsys "../Final Folder/2Darray_pkg.vhd"
ghdl -a --std=08 --ieee=synopsys "../Basic Functions/AbsCValue2.vhd"
ghdl -a --std=08 --ieee=synopsys "../Basic Functions/Adder_IT.vhd"
ghdl -a --std=08 --ieee=synopsys "../Basic Functions/AdderN_Signed.vhd"
ghdl -a --std=08 --ieee=synopsys "../Basic Functions/Average_IT.vhd"
ghdl -a --std=08 --ieee=synopsys "../Basic Functions/AverageN_IT.vhd"
ghdl -a --std=08 --work=lpm --ieee=synopsys "../Basic Functions/MultiplierN_Signed.vhd"
ghdl -a --std=08 --ieee=synopsys "../Basic Functions/MultiplierN_Signed.vhd"
ghdl -a --std=08 --ieee=synopsys "../Basic Functions/Buffer_IT.vhd"
ghdl -a --std=08 --ieee=synopsys "../Basic Functions/ComplexAdderN_Signed.vhd"
ghdl -a --std=08 --ieee=synopsys "../Basic Functions/ComplexMultiplierN_Signed.vhd"
ghdl -a --std=08 --ieee=synopsys "../Basic Functions/Delay_IT.vhd"
ghdl -a --std=08 --ieee=synopsys "../Basic Functions/DelayN.vhd"
ghdl -a --std=08 --ieee=synopsys "../Basic Functions/Expander_NSigned.vhd"
ghdl -a --std=08 --ieee=synopsys "../Basic Functions/Multiplier_IT.vhd"
ghdl -a --std=08 --ieee=synopsys "../Basic Functions/Register_IT.vhd"
ghdl -a --std=08 --ieee=synopsys "../Basic Functions/Register_M.vhd"
ghdl -a --std=08 --ieee=synopsys "../Basic Functions/ROM_IQmap.vhd"
ghdl -a --std=08 --ieee=synopsys "../Basic Functions/Sqrt_IT.vhd"
ghdl -a --std=08 --ieee=synopsys "../Basic Functions/Subtractor_IT.vhd"
ghdl -a --std=08 --ieee=synopsys "../Basic Functions/SubtractorN_Signed.vhd"
ghdl -a --std=08 --ieee=synopsys "../Basic Functions/Sum_N_Signed.vhd"
ghdl -a --std=08 --ieee=synopsys "../Final Folder/ArrayN2ArrayM.vhd"
ghdl -a --std=08 --ieee=synopsys "../Final Folder/ArrayN2ArrayM2.vhd"
ghdl -a --std=08 --ieee=synopsys "../Final Folder/FindROMadrr.vhd"
ghdl -a --std=08 --ieee=synopsys "../Final Folder/LutExpTPhase.vhd"
ghdl -a --std=08 --ieee=synopsys "../Final Folder/RAM_Nsample.vhd"
ghdl -a --std=08 --ieee=synopsys "../Final Folder/ROM_IQmap_Sel.vhd"
ghdl -a --std=08 --ieee=synopsys "../Final Folder/SquareDist.vhd"
ghdl -a --std=08 --ieee=synopsys "../Final Folder/SymbolSelection.vhd"
ghdl -a --std=08 --ieee=synopsys "../Final Folder/DecisionCircuit4QAM.vhd"
ghdl -a --std=08 --ieee=synopsys "../Final Folder/DecisionCircuit16QAM.vhd"
ghdl -a --std=08 --ieee=synopsys "../Final Folder/ErrorTPhase.vhd"
ghdl -a --std=08 --ieee=synopsys "../Final Folder/FindQuad.vhd"
ghdl -a --std=08 --ieee=synopsys "../Final Folder/Min_Array.vhd"
ghdl -a --std=08 --ieee=synopsys "../Final Folder/CPE_BPS.vhd"
ghdl -a --std=08 --ieee=synopsys vhdl_simulation.vhd
ghdl -e --std=08 --ieee=synopsys vhdl_simulation
ghdl -r --std=08 --ieee=synopsys vhdl_simulation
pause
