function createfigure(X1, Y1, X2, YMatrix1, X3, Y2)
%CREATEFIGURE(X1, Y1, X2, YMatrix1, X3, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  YMATRIX1:  matrix of y data
%  X3:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 07-Jun-2018 15:43:19

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Noise');

% Create multiple lines using matrix input to plot
plot1 = plot(X2,YMatrix1);
set(plot1(1),'DisplayName','Signal');
set(plot1(2),'DisplayName','Estimated Noise','LineStyle','--');

% Create plot
plot(X3,Y2,'DisplayName','Reference Noise Points','Marker','+',...
    'LineStyle','none',...
    'Color',[1 0 1]);

% Create xlabel
xlabel('Frequency (Hz)');

% Create title
title({'Signal Spectrum, 16 GBd','Frequency Resolution = 97.66 MHz'});

box(axes1,'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.272619047619047 0.147222226763528 0.317857136098402 0.165476185934884]);

